name: vetki and relaese
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получение кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Подготовка файлов для публикации
      - name: Prepare files for publishing
        run: |
          # Создание директории site
          mkdir -p site
          
          # Создание подпапки с именем версии релиза
          mkdir -p site/${{ github.event.release.tag_name }}
          
          # Копирование всех файлов в папку с версией
          cp -r *.html ru/ en/ site/${{ github.event.release.tag_name }}/
          
          # Модификация ссылок в HTML файлах для корректной работы в подпапке
          find site/${{ github.event.release.tag_name }} -name "*.html" -exec sed -i "s|href=\"../|href=\"/${{ github.event.release.tag_name }}/|g" {} \;
          find site/${{ github.event.release.tag_name }} -name "*.html" -exec sed -i "s|href=\"ru/|href=\"/${{ github.event.release.tag_name }}/ru/|g" {} \;
          find site/${{ github.event.release.tag_name }} -name "*.html" -exec sed -i "s|href=\"en/|href=\"/${{ github.event.release.tag_name }}/en/|g" {} \;

      # Шаг 3: Публикация на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          keep_files: true